### ISSUE TITLE
idea: promote a poll about machine readable data sources in economics

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/intro#10]
Do you write code that imports macroeconomic time series data? 
- [ ] all the time
- [ ] once in a while
- [ ] I don't but people around do a lot
- [ ] I stay away from it 
- [ ] I knew how

Do you feel there is more better data available to work with?
- [ ] yes
- [ ] no

Do you use Excel as much as 3 years ago?
- [ ] even more
- [ ] just the same
- [ ] I allocate a bit more time to other software
- [ ] Excel is history now

Do you write code that imports  macroeconomic time series data? 
- [ ] all the time
- [ ] once in a while
- [ ] I don't but people around do a lot
- [ ] I stay away from it 

What public sources do you use?
- [ ] FRED
- [ ] Quandl
- [ ] OECD API
- [ ] IMF API
- [ ] World bank API
- [ ] national statistics agency any
- [ ] oh, here is a cool link: __________________________

How do you import data?
- [ ] R
- [ ] python pandas
- [ ] econometrics package
- [ ] Excel plugin

What is the nature of work you do macroeconomic data"
- [ ] student assignments / excercises
- [ ] descriptive statistics / visualisation
- [ ] modelling/forecasting

Your affiliation:
- [ ] university
- [ ] central bank or government agency
- [ ] bank or financial sector     
- [ ] other corporate sector
- [ ] non-profit
- [ ] other

**Comment by epogrebnyak** [comment]
@fastali: I edited the poll here - <https://github.com/mini-kep/intro/blob/master/poll.md>, you should be able to see changes in commit diff.

**Comment by epogrebnyak** [comment]
Please note some questions accept multiple answeres and some just one. If we do not have a fuinctionality for this, let it all be multiple answers.

**Comment by epogrebnyak** [comment]
Current draft by @fastali: <https://goo.gl/2wY43R>

**Comment by fastali** [comment]
@epogrebnyak:
Survey updated according to the current [poll.md](https://github.com/mini-kep/intro/blob/master/poll.md).

> Please note some questions accept multiple answeres and some just one. If we do not have a 
> fuinctionality for this, let it all be multiple answers.

[poll.md](https://github.com/mini-kep/intro/blob/master/poll.md) edited to contain information about which questions should have check boxes.

**Comment by fastali** [comment]
@epogrebnyak:
updated survey.

**Comment by epogrebnyak** [comment]
Many thanks, will be putting it on a readme page and need ways to promote the poll.

**Comment by fastali** [comment]
I have some suggestions about promotion of the poll:
*make some social media pages/accounts for the project
*share the survey on multiple economy platforms (Facebook/Vk pages, active economy forums, student platforms)
please advise me if you have any more ideas.
and it would be best if more contributors help spread the poll.

**Comment by epogrebnyak** [comment]
ok, here are some things to sort out
- [ ] how to we see the resuls of the poll from google docs?

Media account is great, but let's do this when we have the landing pages for individual indicators/time series in the app - a comment to inflation change or some other macro event can make a little piece of news. @relique - please note we will need a kind of social media footer for the indicator landing page. 

As of now I will just promote the poll among contributors after we know where the results are. Results are important because people like to look at the graphs, makes them feel more involved.

**Comment by fastali** [comment]
I can add people as contributors to poll. if you give me your e-mail adres I can add you to the list of contributors so you can edit the poll or see results.

**Comment by fastali** [comment]
we can also ask for e-mail adresses of the people who take the survey, should I include that feature?
