### ISSUE TITLE
intro: collect Travis and Codecov status from repos, make a markdown table 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/intro#5]
- <https://github.com/mini-kep/parser-rosstat-kep>
- <https://github.com/mini-kep/frontend-app>

**Comment by epogrebnyak** [comment]
for rendering markdown can use: <https://github.com/mini-kep/parser-template/blob/master/to_markdown.py>

**Comment by epogrebnyak** [comment]
```python 

def make_md_badge_travis(repo_name): 
    line1 = f"[![Build Status](https://travis-ci.org/mini-kep/{repo_name}.svg?branch=master)]"
    line2 = f"(https://travis-ci.org/mini-kep/{repo_name})"
    return line1+line2

```

**Comment by Tcheutchoua-Steve** [comment]
```python

def make_md_badge_codecov(repo_name): 
    line1 = f"[![](https://codecov.io/gh/mini-kep/{repo_name}/branch/master/graphs/badge.svg)]"
    line2 = f"(https://codecov.io/gh/mini-kep/{repo_name})"
    return line1+line2
```

**Comment by epogrebnyak** [comment]
Should read: intro: collect Travis and Codecov status for two repos, make a markdown table #5

**Comment by epogrebnyak** [comment]
| Repo | Tests | Coverage |
| ---- | ----- | -------- |
| parser-rosstat-kep | [![](https://travis-ci.org/mini-kep/parser-rosstat-kep.svg?branch=master)](https://travis-ci.org/mini-kep/parser-rosstat-kep) | [![](https://codecov.io/gh/mini-kep/parser-rosstat-kep/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/parser-rosstat-kep) |
| frontend-app | [![](https://travis-ci.org/mini-kep/frontend-app.svg?branch=master)](https://travis-ci.org/mini-kep/frontend-app) | [![](https://codecov.io/gh/mini-kep/frontend-app/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/frontend-app) |

**Comment by epogrebnyak** [comment]
```python
def md_link(what, link):
    return f'[{what}]({link})'

def md_img(img_url, alt=''):
    return f'![{alt}]({img_url})'

def md_img_link(img_url, link_url):
    img_str = md_img(img_url)
    return md_link(what=img_str, link=link_url)                  

def make_badge_travis(repo_name): 
    base_url = f'https://travis-ci.org/mini-kep/{repo_name}'
    svg_url = f'{base_url}.svg?branch=master'
    return md_img_link(svg_url, base_url)

def make_badge_codecov(repo_name): 
    base_url = f'https://codecov.io/gh/mini-kep/{repo_name}'
    svg_url = f'{base_url}/branch/master/graphs/badge.svg'
    return md_img_link(svg_url, base_url)

def to_markdown(table):
    """Translate *table* list of strings to markdown. 
       Use first row in *table* as header.       
    """    
    header = table[0]
    horiz = ["-" * len(x) for x in header]
    body = table[1:]
    table = [header, horiz]
    table.extend(body)
    
    def add_dividers(row):
        inner_part = " | ".join(row) 
        return f"| {inner_part} |"
    
    table = [add_dividers(row) for row in table]    
    return '\n'.join(table)

if __name__ == "__main__":
    repos = ['parser-rosstat-kep', 
             'parser-template',
             'db',
             'frontend-app']
    rows = [[repo, 
             make_badge_travis(repo), 
             make_badge_codecov(repo)] 
             for repo in repos]
    table = [['Repo', 'Tests', 'Coverage']]
    table.extend(rows)
    md_table = to_markdown(table)
    print(md_table)
    
    doc1 = ("[![]"
            "(https://travis-ci.org/mini-kep/parser-rosstat-kep.svg?branch=master)]"
            "(https://travis-ci.org/mini-kep/parser-rosstat-kep)")
    
    assert make_badge_travis('parser-rosstat-kep') == doc1

```

**Comment by epogrebnyak** [comment]
| Repo | Tests | Coverage |
| ---- | ----- | -------- |
| [parser-rosstat-kep](https://github.com/mini-kep/parser-rosstat-kep) | [![](https://travis-ci.org/mini-kep/parser-rosstat-kep.svg?branch=master)](https://travis-ci.org/mini-kep/parser-rosstat-kep) | [![](https://codecov.io/gh/mini-kep/parser-rosstat-kep/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/parser-rosstat-kep) |
| [parser-template](https://github.com/mini-kep/parser-template) | [![](https://travis-ci.org/mini-kep/parser-template.svg?branch=master)](https://travis-ci.org/mini-kep/parser-template) | [![](https://codecov.io/gh/mini-kep/parser-template/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/parser-template) |
| [db](https://github.com/mini-kep/db) | [![](https://travis-ci.org/mini-kep/db.svg?branch=master)](https://travis-ci.org/mini-kep/db) | [![](https://codecov.io/gh/mini-kep/db/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/db) |
| [frontend-app](https://github.com/mini-kep/frontend-app) | [![](https://travis-ci.org/mini-kep/frontend-app.svg?branch=master)](https://travis-ci.org/mini-kep/frontend-app) | [![](https://codecov.io/gh/mini-kep/frontend-app/branch/master/graphs/badge.svg)](https://codecov.io/gh/mini-kep/frontend-app) |
